Issue 3 user can edit an entry
julieluangpraxay/code-journal pull request #8
Opened 2023-08-06 20:29 UTC by julieluangpraxay

https://github.com/julieluangpraxay/code-journal/assets/130415142/296c0429-75c1-4d9e-9c87-faa6b6199cb3

2023-08-06 21:00 UTC, shawnkost requested changes
Some changes here Julie!

2023-08-06 21:00 UTC, shawnkost commented on js/main.js
>  });
`viewSwap` and `toggleNoEntries` should be getting called here instead

2023-08-06 21:00 UTC, shawnkost commented on js/main.js
> +    toggleNoEntries();
This will be deleted after the other change

2023-08-06 21:00 UTC, shawnkost commented on js/main.js
> +    data.editing.entryId = formData.entryId;
This should be swapped

2023-08-06 21:00 UTC, shawnkost commented on js/main.js
> +    data.entries[data.entries.length - formData.entryId] = formData;
This won't always work. I suggest using another method of finding the entry you want to update,  like looping over it instead

2023-08-06 21:00 UTC, shawnkost commented on js/main.js
> +    viewSwap('entry-form');
I would move this down to the bottom of the function, so that we only swap after all the `input`s are filled in

2023-08-06 23:44 UTC, julieluangpraxay commented
https://github.com/julieluangpraxay/code-journal/assets/130415142/420ed7ec-fb37-4b82-a8db-6910f84e7047

2023-08-07 01:55 UTC, shawnkost requested changes
Few more changes here Julie!

2023-08-07 01:55 UTC, shawnkost commented on js/main.js
> -    $image.src = './images/placeholder-image-square.jpg';
This should stay

2023-08-07 01:55 UTC, shawnkost commented on js/main.js
> +  toggleNoEntries();
You should call `$submitForm.reset()` here instead. This way we always reset the form after creating a new entry or editing an entry

2023-08-07 01:55 UTC, shawnkost commented on js/main.js
> +        $submitForm.reset();
Delete this

2023-08-08 01:03 UTC, shawnkost approved these changes
👍🏻

2023-08-08 01:58 UTC, merged